# SWE-Bench Optimal Configuration
# Based on comprehensive benchmark testing across 10 configurations
# GitHub Issue: #610

# WINNER: mesh-optimization-8agents
# Performance: 97.7% success rate, 11.1s average duration
# Combined Score: 0.970

# Optimal Settings
coordination_mode: mesh
strategy: optimization
max_agents: 8

# Performance Characteristics
performance:
  success_rate: 97.7%
  avg_duration: 11.1s
  combined_score: 0.970
  
# Alternative High-Performance Configurations

alternates:
  # 2nd Place: mesh-optimization-10agents
  high_parallelism:
    coordination_mode: mesh
    strategy: optimization
    max_agents: 10
    success_rate: 94.0%
    avg_duration: 11.6s
    
  # 3rd Place: hierarchical-development-8agents
  balanced:
    coordination_mode: hierarchical
    strategy: development
    max_agents: 8
    success_rate: 87.4%
    avg_duration: 12.9s

# Task-Specific Recommendations

task_specific:
  code_generation:
    strategy: development
    mode: hierarchical
    agents: 8
    
  bug_fix:
    strategy: optimization
    mode: mesh
    agents: 8
    
  refactoring:
    strategy: optimization
    mode: mesh
    agents: 5
    
  testing:
    strategy: testing
    mode: hierarchical
    agents: 5
    
  documentation:
    strategy: analysis
    mode: centralized
    agents: 3
    
  code_review:
    strategy: analysis
    mode: mesh
    agents: 5
    
  performance:
    strategy: optimization
    mode: distributed
    agents: 10

# Usage Example
# swarm-bench swe-bench run --mode mesh --strategy optimization --agents 8