global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'litellm-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # LiteLLM Proxy metrics
  - job_name: 'litellm-proxy-1'
    static_configs:
      - targets: ['litellm-1:9090']
        labels:
          instance: 'proxy-1'
          service: 'litellm'

  - job_name: 'litellm-proxy-2'
    static_configs:
      - targets: ['litellm-2:9091']
        labels:
          instance: 'proxy-2'
          service: 'litellm'

  - job_name: 'litellm-proxy-3'
    static_configs:
      - targets: ['litellm-3:9092']
        labels:
          instance: 'proxy-3'
          service: 'litellm'

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # Nginx exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'loadbalancer'